var RestaurantConstants = {
	RESTAURANT_RECEIVED: "RESTAURANT_RECEIVED",
	RESTAURANTS_RECEIVED: "RESTAURANTS_RECEIVED",
	CLEAR_SEARCH_RESTAURANTS: "CLEAR_SEARCH_RESTAURANTS"
};

module.exports = RestaurantConstants;
